### PR TITLE
Factories and Seeders Feedback

### PR DESCRIPTION
**Pull request by abem93**
This is a pull request to get some feedback on the factories and seeders that I have so far. I'd like to make sure that best practices are being followed and that the implementation align  the model structures.

Any and all feedback is welcome.

### CODE REVIEW

**Comment by jason-klein** [comment]
@abem93 I like what you have done so far! Here are two general changes to consider:

1. Could any dates also be a future date? If so, update factory so end date could be future date instead of `now()`.  Examples:
`database/factories/ModuleAssignmentFactory.php` `event_date`
`database/factories/ProgramAssignmentFactory.php` `start_date`

2. You may want to lookup a random existing related Model instead of creating a new related Model for every relationship in every new record. For example, your live application will have multiple program assignments for a single program. Your factory will always create a new program for each program assignment.

PM me if you want help with item 2 above.

**Comment by abem93** [comment]
@jason-klein I went ahead and used the recycle method, which in theory should use existing models instead of creating a new one.

**Comment by jason-klein** [comment]
@abem93 Your code changes and additions are looking great, but I am unable to run the seeders without errors.

**Can you please test your seeders by running one of the following commands?** Resolve any seeding errors. Repeat until you no longer see errors during seeding.

`sail artisan migrate:fresh --seed`
or
`artisan migrate:fresh --seed`

It doesn't seem like you've tested your seeding yet. Here are the first few errors I am receiving and recommended fixes.

### Database\Seeders\ResponsiblePartySeeder

`SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: responsible_parties.user_id (Connection: sqlite, SQL: insert into "responsible_parties" ("id", "phone_number", "role", "updated_at", "created_at") values (e228c891-f176-3119-ba0f-c27da61becc6, 515.922.8041, intake, 2024-09-11 00:59:09, 2024-09-11 00:59:09))`
  * FIX: Update Factory to populate `user_id` field from an existing User.

`SQLSTATE[23000]: Integrity constraint violation: 19 CHECK constraint failed: role (Connection: sqlite, SQL: insert into "responsible_parties" ("id", "user_id", "phone_number", "role", "updated_at", "created_at") values (ec9119fe-3e11-3aac-aa98-888e8f019ad8, 9cfaf556-f1a8-4dc6-8884-c7a4f4a2ee9d, 1-681-295-5923, admin, 2024-09-11 01:05:18, 2024-09-11 01:05:18))`
  * FIX: Factory is trying to create ResponsibleParty records with invalid roles ('admin', 'program director', 'director', 'auditor', 'intake', 'caseManager', 'region director', 'other'). Either update factory to use valid roles or update `responsible_parties` table migration to include all valid `role` values in ENUM list.

### Database\Seeders\DadSeeder

`  SQLSTATE[HY000]: General error: 1 table dads has no column named at_contact_number (Connection: sqlite, SQL: insert into "dads" ("user_id", "region_id", "street_address", "city", "zip_code", "employer", "cell_phone_number", "home_phone_number", "work_phone_number", "at_contact_number", "marital_status", "ethnicity", "monthly_child_support", "id", "updated_at", "created_at") values (9cfaf6db-7bfc-44bc-9db8-5e885f4be6e9, 1ca8c854-5af9-4a5f-8dc7-404d480a2162, 92737 Billie Pass, O'Haraland, 22833-6314, Gerlach, Bednar and Heidenreich, 318.201.4597, 385-519-9367, 445-857-8956, 1-409-510-4002, married, africanAmerican, 960.19, 9cfaf6db-940a-404f-ab51-df187e399b6c, 2024-09-11 01:09:33, 2024-09-11 01:09:33))`

  * FIX: Correct typo in field name `at_contact_number`. Likely supposed to be `alt_contact_number`.


I think you'll find most of these errors are easy to fix as you find them. If not, send questions in the PR or let's connect next Tuesday! :)

**Comment by abem93** [comment]
@jason-klein seeders are seeding.

**Review by jason-klein — APPROVED** [review]
Changes look good! Confirmed I can perform `artisan migrate:fresh --seed` without any errors. Thanks @abem93!

**Pull request merged**
